/*
MASV: 47.01.104.045
HO TEN: PHAN VU TUAN ANH
LAB: 03
NGAY: 01/04/2024
*/

USE master
GO

DROP DATABASE EMPLOYEE
GO

CREATE DATABASE EMPLOYEE
GO

USE EMPLOYEE
GO

CREATE TABLE Employee
(
	EMPLOYEEID NVARCHAR(20) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	SALARY VARBINARY(MAX),
	USERNAME NVARCHAR(100) NOT NULL,
	PASSWORD VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_Employee PRIMARY KEY (EMPLOYEEID)
)

CREATE TABLE Class
(
	CLASSID NVARCHAR(20) NOT NULL,
	CLASSNAME NVARCHAR(100) NOT NULL,
	EMPLOYEEID NVARCHAR(20),
	CONSTRAINT PK_Class PRIMARY KEY (CLASSID),
	CONSTRAINT FK_Employee FOREIGN KEY (EMPLOYEEID) REFERENCES Employee (EMPLOYEEID)
)

CREATE TABLE Student
(
	STUDENTID NVARCHAR(20) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	BDAY DATE,
	ADDRESS NVARCHAR(200),
	CLASSID NVARCHAR(20) NOT NULL,
	USERNAME NVARCHAR(100) NOT NULL,
	PASSWORD VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_Student PRIMARY KEY (STUDENTID),
	CONSTRAINT FK_Class FOREIGN KEY (CLASSID) REFERENCES Class (CLASSID)
)
GO

CREATE MASTER KEY ENCRYPTION BY  PASSWORD = '4701104045';
Go 

CREATE CERTIFICATE StuID  
   WITH SUBJECT = 'Student ID for encryption';  
GO  

CREATE SYMMETRIC KEY StudentID_Key  
    WITH ALGORITHM = AES_256  
    ENCRYPTION BY CERTIFICATE StuID;  
GO  

-- Check if key existed
SELECT * FROM sys.symmetric_keys
WHERE NAME = '##MS_DatabaseMasterKey##';
GO

-- New column for encrypted salary.  
ALTER TABLE Employee
    ADD Salary_Encrypted VARBINARY(MAX);   
GO

exec sp_columns Employee
GO