/*
FILE SQL THU TU 1
HOTEN - MASV: 
	PHAN VU TUAN ANH - 47.01.104.045
	LAI THI ANH DANG - 47.01.104.058
	NGUYEN TRAN ANH LINH - 47.01.104.123
	VO KIEN PHU - 47.01.104.160
LAB: 03 - NHOM 
NGAY: 05/04/2024
*/
USE master
DROP DATABASE QLSV
GO

CREATE DATABASE QLSV
GO

USE QLSV
GO

CREATE TABLE NhanVien
(
	MANV	VARCHAR(20) NOT NULL,
	HOTEN	NVARCHAR(100) NOT NULL,
	EMAIL	VARCHAR(20),
	LUONG	VARBINARY(MAX),
	TENDN	NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY	VARCHAR(20)
	CONSTRAINT PK_NhanVien PRIMARY KEY (MANV)
)

CREATE TABLE Lop
(
	MALOP	VARCHAR(20) NOT NULL,
	TENLOP	NVARCHAR(100) NOT NULL,
	MANV	VARCHAR(20),
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
	CONSTRAINT FK_NhanVien FOREIGN KEY (MANV) REFERENCES NhanVien (MANV)
)

CREATE TABLE SinhVien
(
	MASV		NVARCHAR(20) NOT NULL,
	HOTEN		NVARCHAR(100) NOT NULL,
	NGAYSINH	DATETIME,
	DIACHI		NVARCHAR(200),
	MALOP		VARCHAR(20) NOT NULL,
	TENDN		NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_SinhVien PRIMARY KEY (MASV),
	CONSTRAINT FK_Lop FOREIGN KEY (MALOP) REFERENCES Lop (MALOP)
)

CREATE TABLE HocPhan
(
	MAHP VARCHAR(20) NOT NULL,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
	CONSTRAINT PK_HocPhan PRIMARY KEY (MAHP)
)

CREATE TABLE BangDiem (
    MASV		NVARCHAR(20),
    MAHP		VARCHAR(20),
    DIEMTHI		VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP),
    CONSTRAINT FK_BangDiem_SinhVien FOREIGN KEY (MASV) REFERENCES SinhVien(MASV),
    CONSTRAINT FK_BangDiem_HocPhan FOREIGN KEY (MAHP) REFERENCES HocPhan(MAHP)
);
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'NgoiNhaHanhPhuc';
GO

SELECT * FROM sys.symmetric_keys
WHERE NAME = '##MS_DatabaseMasterKey##';
GO

SELECT * FROM sys.asymmetric_keys
GO

/*
SELECT * FROM NhanVien
GO
*/

/*
-- Tạo khoá bất đối xứng
CREATE ASYMMETRIC KEY QLNV_ASYMKEY
WITH ALGORITHM = RSA_2048;

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'BT-7274';
GO

CREATE CERTIFICATE StuID  
	WITH SUBJECT = 'SinhVien ID for encryption';  
GO  

CREATE SYMMETRIC KEY MASV_Key  
    WITH ALGORITHM = AES_256  
    ENCRYPTION BY CERTIFICATE StuID;  
GO  

-- Check if key existed
SELECT * FROM sys.symmetric_keys
WHERE NAME = '##MS_DatabaseMasterKey##';
GO

-- New column for encrypted LUONG.  
ALTER TABLE NhanVien
    ADD LUONG_Encrypted VARBINARY(MAX);   
GO

exec sp_columns NhanVien
GO
*/