/*
FILE SQL THU TU 2
HOTEN - MASV: 
	PHAN VU TUAN ANH - 47.01.104.045
	LAI THI ANH DANG - 47.01.104.058
	NGUYEN TRAN ANH LINH - 47.01.104.123
	VO KIEN PHU - 47.01.104.160
LAB: 03 - NHOM 
NGAY: 05/04/2024
*/

USE QLSV
GO

CREATE PROCEDURE SP_INS_PUBLIC_SINHVIEN (
	@MASV		NVARCHAR(20),
	@HOTEN		NVARCHAR(100),
	@NGAYSINH	DATETIME,
	@DIACHI		NVARCHAR(200),
	@MALOP		NVARCHAR(20),
	@TENDN		NVARCHAR(100),
	@MATKHAU	NVARCHAR(100) -- Will be inserted as text
)
AS
BEGIN
	DECLARE @Enc_PASSWORD VARBINARY(MAX)
	SET @Enc_PASSWORD = CAST(HASHBYTES('SHA1', @MATKHAU) AS VARBINARY(MAX))
	INSERT INTO SinhVien (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
	VALUES ( @MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @Enc_PASSWORD)
END
GO

CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN (
	@MANV		NVARCHAR(20),
	@HOTEN		NVARCHAR(100),
	@EMAIL		VARCHAR(20),
	@LUONGCB	INT,			-- Will be inserted as text
	@TENDN		NVARCHAR(100),
	@MK			NVARCHAR(100)	-- Will be inserted as text
)
AS
BEGIN
	DECLARE @PUBKEY NVARCHAR(20) = @MANV;

	-- Encrypt Salary
	-- Cna't execute creating asymkey normally so using SQL Statment is a must
	-- RSA_512 is no long supported since 2022 by SQL SERVER so I'll use 2048
	DECLARE @Enc_LUONG VARBINARY(MAX);
	DECLARE @SQL_Statement NVARCHAR(MAX);
	SET @SQL_Statement = 'CREATE ASYMMETRIC KEY ' + QUOTENAME(@PUBKEY) + '
				WITH ALGORITHM = RSA_2048
				ENCRYPTION BY PASSWORD = ''' + @MK + ''';
				';
	EXEC(@SQL_Statement);

	SET @Enc_LUONG = CAST(ENCRYPTBYASYMKEY(ASYMKEY_ID(@PUBKEY), CONVERT(VARBINARY(MAX), @LUONGCB)) AS VARBINARY(MAX));
	
	-- Encrypt Pass
	DECLARE @Enc_PASSWORD VARBINARY(MAX);
	SET @Enc_PASSWORD = CAST(HASHBYTES('SHA1', @MK) AS VARBINARY(MAX));

	INSERT INTO NhanVien(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@MANV, @HOTEN, @EMAIL, @Enc_LUONG, @TENDN, @Enc_PASSWORD, @PUBKEY);
END
GO

/*
exec sp_columns NhanVien
GO
*/

CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN(
		@TENDN NVARCHAR(100),
		@MK NVARCHAR(100))
AS
BEGIN
	SELECT MANV, HOTEN, EMAIL, CAST(DECRYPTBYASYMKEY(ASYMKEY_ID(PUBKEY), LUONG, @MK)AS INT) AS 'LUONGCB' FROM NhanVien
END
GO

 EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
 GO
 EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'NVB@', 3400000, 'NVB', 'abcd12'
 GO
 EXEC SP_INS_PUBLIC_NHANVIEN 'NV03', 'NGUYEN VAN C', 'NVC@', 3500000, 'NVC', 'abcd13'
 GO

 EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', 'abcd12'
 GO
 EXEC SP_SEL_PUBLIC_NHANVIEN 'NVB', 'abcd12' 
 GO
 EXEC SP_SEL_PUBLIC_NHANVIEN 'NVC', 'abcd13' 
 GO

SELECT * FROM NhanVien
GO

DELETE FROM NhanVien
GO

DROP PROCEDURE SP_INS_PUBLIC_SINHVIEN
DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO


/*
SELECT * FROM sys.asymmetric_keys
GO
*/
DELETE FROM sys.asymmetric_keys
GO

DROP DATABASE QLSV
GO