/*
HOTEN - MASV: 
	PHAN VU TUAN ANH - 47.01.104.045
	LAI THI ANH DANG - 47.01.104.058
	NGUYEN TRAN ANH LINH - 47.01.104.123
	VO KIEN PHU - 47.01.104.160
LAB: 03 - NHOM 
NGAY: 05/04/2024
*/

-- Xoá DB khi lỗi
USE master
GO

DROP DATABASE QLSV_Lai_Tap
GO

-- Tạo DB + Tables nè
CREATE DATABASE QLSV_Lai_Tap
GO 

USE QLSV_Lai_Tap
GO

CREATE TABLE NhanVien
(
	MANV	VARCHAR(20) NOT NULL,
	HOTEN	NVARCHAR(100) NOT NULL,
	EMAIL	VARCHAR(20),
	LUONG	VARBINARY(MAX),
	TENDN	NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY	VARCHAR(20)
	CONSTRAINT PK_NhanVien PRIMARY KEY (MANV)
)

CREATE TABLE Lop
(
	MALOP	VARCHAR(20) NOT NULL,
	TENLOP	NVARCHAR(100) NOT NULL,
	MANV	VARCHAR(20),
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
	CONSTRAINT FK_NhanVien FOREIGN KEY (MANV) REFERENCES NhanVien (MANV)
)

CREATE TABLE SinhVien
(
	MASV		NVARCHAR(20) NOT NULL,
	HOTEN		NVARCHAR(100) NOT NULL,
	NGAYSINH	DATETIME,
	DIACHI		NVARCHAR(200),
	MALOP		VARCHAR(20) NOT NULL,
	TENDN		NVARCHAR(100) NOT NULL,
	MATKHAU		VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_SinhVien PRIMARY KEY (MASV),
	CONSTRAINT FK_Lop FOREIGN KEY (MALOP) REFERENCES Lop (MALOP)
)

CREATE TABLE HocPhan
(
	MAHP VARCHAR(20) NOT NULL,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
	CONSTRAINT PK_HocPhan PRIMARY KEY (MAHP)
)

CREATE TABLE BangDiem (
    MASV		NVARCHAR(20),
    MAHP		VARCHAR(20),
    DIEMTHI		VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP),
    CONSTRAINT FK_BangDiem_SinhVien FOREIGN KEY (MASV) REFERENCES SinhVien(MASV),
    CONSTRAINT FK_BangDiem_HocPhan FOREIGN KEY (MAHP) REFERENCES HocPhan(MAHP)
);
GO

SELECT * FROM NhanVien
GO
SELECT * FROM Lop
GO
SELECT * FROM SinhVien
GO
SELECT * FROM HocPhan
GO
SELECT * FROM BangDiem
GO


-- Tạo Procedures nè(Đang kẹt ở mục giải mã thông tin lương nhân viên)
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN (
	@MANV		NVARCHAR(20),
	@HOTEN		NVARCHAR(100),
	@EMAIL		VARCHAR(20),
	@LUONGCB	INT,			-- Will be inserted as text
	@TENDN		NVARCHAR(20),
	@MK			NVARCHAR(100)	-- Will be inserted as text
)
AS
BEGIN
	DECLARE @LUONG VARBINARY(MAX);
	DECLARE @PASSWORD VARBINARY(MAX);
	DECLARE @PUBKEY NVARCHAR(20) = @MANV;
	
	-- Encrypt Salary
	-- Create asymkey
	DECLARE @SQL NVARCHAR(MAX);
	SET @SQL = 'CREATE ASYMMETRIC KEY ' + QUOTENAME(@PUBKEY) + '
				WITH ALGORITHM = RSA_2048
				ENCRYPTION BY PASSWORD = ''' + @MK + ''';
				';
	EXEC(@SQL);
	SET @LUONG = CAST(ENCRYPTBYASYMKEY(ASYMKEY_ID(@PUBKEY), CONVERT(VARBINARY(MAX), @LUONGCB)) AS VARBINARY(MAX));
	
	-- Encrypt Pass
	SET @PASSWORD = CAST(HASHBYTES('SHA1', @MK) AS VARBINARY(MAX));

	INSERT INTO NhanVien(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @PASSWORD, @PUBKEY)
END
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'NVB@', 3400000, 'NVB', 'abcd12'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV03', 'NGUYEN VAN C', 'NVC@', 3500000, 'NVC', 'abcd12'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV04', 'NGUYEN VAN D', 'NVC@', 2500000, 'NVD', 'abcd12'
GO

SELECT * FROM NHANVIEN
GO
-- Bắt đầu failed tại đây
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN(
		@TENDN NVARCHAR(20),
		@MK NVARCHAR(100))
AS
BEGIN
	SELECT MANV,HOTEN,EMAIL, CAST( DECRYPTBYASYMKEY( ASYMKEY_ID(PUBKEY), LUONG, @MK) AS INT) AS 'LUONGCB' FROM NhanVien
END
GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', 'abcd12' 
GO

UPDATE NHANVIEN
SET HOTEN = 'Tran Van B'
WHERE MANV = 'NV02';
GO


CREATE PROCEDURE SP_INS_PUBLIC_SINHVIEN (
	@MASV		NVARCHAR(20),
	@HOTEN		NVARCHAR(100),
	@NGAYSINH	DATETIME,
	@DIACHI		NVARCHAR(200),
	@MALOP		NVARCHAR(20),
	@TENDN		NVARCHAR(100),
	@MATKHAU	NVARCHAR(100) -- Will be inserted as text
)
AS
BEGIN
	DECLARE @Enc_PASSWORD VARBINARY(MAX)
	SET @Enc_PASSWORD = CAST(HASHBYTES('MD5', @MATKHAU) AS VARBINARY(MAX))
	INSERT INTO SinhVien (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
	VALUES ( @MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @Enc_PASSWORD)
END
GO

INSERT INTO Lop(MALOP, TENLOP, MANV)
			VALUES	('CNTT-K47', 'Cong nghe thong tin K47', NULL),
					('TT-K47', 'Truyen thong K47', NULL),
					('NNA-K47', 'Ngon ngu Anh K47', NULL),
					('QLXD-K47', 'Quan ly xay dung K47', NULL)
GO


EXEC SP_INS_PUBLIC_SINHVIEN 'ST01', 'PHAN VU TUAN ANH', '2001-01-01', 'Binh Thanh', 'TT-K47', 'PVTA', '111111'
EXEC SP_INS_PUBLIC_SINHVIEN 'ST02', 'LAI THI ANH DANG', '2002-02-02', 'Binh Thanh', 'NNA-K47', 'LTAD', '222222'
EXEC SP_INS_PUBLIC_SINHVIEN 'ST03', 'NGUYEN TRAN ANH LINH', '2003-03-03', 'Hoc Mon', 'CNTT-K47', 'NTAL', '333333'
EXEC SP_INS_PUBLIC_SINHVIEN 'ST04', 'VO KIEN PHU', '2004-04-04', 'Hoc Mon', 'CNTT-K47', 'VKP', '4444'
GO

SELECT * FROM SinhVien
GO

-- Bắt đầu nhét thông tin vào nè(phần này sẽ lỗi vì tui chưa đụng tới nhiều)
-- Nhét thông tin nhân viên(thành công)
-- Nhét thông tin sinh viên(thành công)
/*
EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'NVB@', 3400000, 'NVB', 'abcd12'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV03', 'NGUYEN VAN C', 'NVC@', 3500000, 'NVC', 'abcd13'
GO
EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', 'abcd12'
GO
EXEC SP_SEL_PUBLIC_NHANVIEN 'NVB', 'abcd12' 
GO
EXEC SP_SEL_PUBLIC_NHANVIEN 'NVC', 'abcd13' 
GO
*/

-- Test lấy thông tin nhân viên ra(không thành công)



-- Đây là để ông test procedures, tables không ổn thì cứ drop rồi sửa lại

/*
DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO
*/


SELECT * FROM sys.asymmetric_keys
GO