create database QLSVNhom
go
USE QLSVNhom
go
--drop DATABASE QLSVNhom
/*---------------------------------------------------------- 
MASV: 
HO TEN CAC THANH VIEN NHOM: 
LAB: 03 - NHOM 
NGAY:  
----------------------------------------------------------*/


--CAU LENH TAO DB 


CREATE TABLE SINHVIEN
(
    MASV VARCHAR(20) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME ,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20), -- tham chieu den malop ben bang lop
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(20) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100),
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20) -- ten khoa cong khai
)
GO

CREATE TABLE LOP
(
    MALOP VARCHAR(20) NOT NULL PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20) -- khoa ngoai tham chieu den bang nhanvien
)
GO

CREATE TABLE HOCPHAN
(
    MAHP VARCHAR(20) NOT NULL PRIMARY KEY,
    TENHP NVARCHAR NOT NULL,
    SOTC INT
)
GO
CREATE TABLE BANDIEM
(
    MASV VARCHAR(20) NOT NULL, 
    MAHP VARCHAR(20) NOT NULL,
    DIEMTHI VARBINARY(MAX),
    PRIMARY KEY (MASV,MAHP)
)
GO



ALTER TABLE BANDIEM
ADD CONSTRAINT fk_constraint_BANDIEM_HOCPHAN
FOREIGN KEY (MAHP)
REFERENCES HOCPHAN(MAHP);
go

ALTER TABLE BANDIEM
ADD CONSTRAINT fk_constraint_BANDIEM_SINHVIEN
FOREIGN KEY (MASV)
REFERENCES SINHVIEN(MASV);
go



ALTER TABLE LOP
ADD CONSTRAINT fk_constraint_LOP_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV);
go

ALTER TABLE SINHVIEN
ADD CONSTRAINT fk_constraint_SINHVIEN_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP);
go


--i)
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
    (
    @MANV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONGCB INT,
    @TENDN NVARCHAR(20),
    @MK NVARCHAR(100)
)
AS
BEGIN
    DECLARE @PASS VARBINARY(MAX), @SALARY VARBINARY(MAX), @PUBKEY NVARCHAR(20) = @MANV;
	SET @PASS = CAST( HASHBYTES('SHA1', @MK) AS varbinary(MAX) );
	-- thuan toan RSA_512 tu nam 2022 da khong con duoc ho tro trong sql server nua
	DECLARE @SQL NVARCHAR(MAX);
	SET @SQL = 'CREATE ASYMMETRIC KEY ' + QUOTENAME(@PUBKEY) + '
				WITH ALGORITHM = RSA_2048
				ENCRYPTION BY PASSWORD = ''' + @MK + ''';
				';

	-- tao khoa doi bat doi xung
	EXEC(@SQL);
	SET @SALARY = CAST(ENCRYPTBYASYMKEY(ASYMKEY_ID(@PUBKEY),CONVERT(VARBINARY(MAX),@LUONGCB)) AS varbinary(max));

	INSERT INTO NHANVIEN (MANV,HOTEN,EMAIL,LUONG,TENDN,MATKHAU,PUBKEY) VALUES
						(@MANV,@HOTEN,@EMAIL,@SALARY,@TENDN,@PASS,@PUBKEY)
		
END
go
EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
	
SELECT * FROM NHANVIEN

GO
---II)
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN(
		@TENDN NVARCHAR(20),
		@MK NVARCHAR(100))
AS
BEGIN
	
	SELECT MANV,HOTEN,EMAIL, CAST( DECRYPTBYASYMKEY( ASYMKEY_ID(PUBKEY),LUONG,@MK) AS int) AS 'LUONGCB' FROM NHANVIEN
END

EXEC SP_SEL_PUBLIC_NHANVIEN 'NV01', 'abcd12' 
SELECT * FROM NHANVIEN




