use QLBongDa
go


CREATE PROCEDURE SP_SEL_NO_ENCRYPT (
	@TenCLB NVARCHAR(100), 
	@TenQG NVARCHAR(60))
AS
BEGIN
	SELECT MACT,HOTEN,NGAYSINH,DIACHI,VITRI 
	FROM CAUTHU 
	INNER JOIN CAULACBO 
	ON CAUTHU.MACLB = CAULACBO.MACLB
	INNER JOIN QUOCGIA
	ON  CAUTHU.MAQG = QUOCGIA.MAQG
	WHERE TENCLB = @TenCLB AND TENQG = @TenQG
END
go


create proc SP_SEL_ENCRYPT
@TenCLB nvarchar(100),
@TenQG nvarchar(60)
with encryption
as
begin
select MACT, HOTEN, NGAYSINH, DIACHI, VITRI
from CAUTHU, CAULACBO, QUOCGIA
where CAUTHU.MACLB = CAULACBO.MACLB and CAUTHU.MAQG = QUOCGIA.MAQG
and CAULACBO.TENCLB = @TenCLB and QUOCGIA.TENQG = @TenQG
end

exec SP_SEL_NO_ENCRYPT N'SHB ĐÀ NẴNG',N'Brazil'
exec SP_SEL_ENCRYPT N'SHB Đà Nẵng', 'Brazil'
