USE QLBongDa
go
CREATE PROCEDURE SP_SEL_NO_ENCRYPT (
	@TenCLB NVARCHAR(100), 
	@TenQG NVARCHAR(60))
AS
BEGIN
	SELECT MACT,HOTEN,NGAYSINH,DIACHI,VITRI,TENCLB,TENQG 
	FROM CAUTHU 
	INNER JOIN CAULACBO 
	ON CAUTHU.MACLB = CAULACBO.MACLB
	INNER JOIN QUOCGIA
	ON  CAUTHU.MAQG = QUOCGIA.MAQG
	WHERE TENCLB = @TenCLB AND TENQG = @TenQG
END

EXECUTE SP_SEL_NO_ENCRYPT N'SHB ĐÀ NẴNG',N'Brazil'