use QLBongDa
go

-- Câu 1
CREATE VIEW vCau1 AS
SELECT CAUTHU.MACT, CAUTHU.HOTEN, CAUTHU.NGAYSINH, CAUTHU.DIACHI, CAUTHU.VITRI
FROM CAUTHU
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE CAULACBO.TENCLB = N'SHB ĐÀ NẴNG' AND QUOCGIA.TENQG = 'Brazil';

-- Câu 2
create view vCau2 as
SELECT TRANDAU.MATRAN, TRANDAU.NGAYTD, SANVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN CAULACBO AS CLB1 ON TRANDAU.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO AS CLB2 ON TRANDAU.MACLB2 = CLB2.MACLB
INNER JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
WHERE TRANDAU.VONG = 3 AND TRANDAU.NAM = 2009;

select * from vCau2

-- Câu 3
create view vCau3 as
SELECT TRANDAU.MATRAN, TRANDAU.NGAYTD, SANVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN CAULACBO AS CLB1 ON TRANDAU.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO AS CLB2 ON TRANDAU.MACLB2 = CLB2.MACLB
INNER JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
WHERE TRANDAU.VONG = 3 AND TRANDAU.NAM = 2009;


-- Câu 4
create view vCau4 as
SELECT CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(CAUTHU.MACT) AS SoLuongCauThuNuocNgoai
FROM CAULACBO
INNER JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG != N'Việt Nam'
GROUP BY CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI
HAVING COUNT(CAUTHU.MACT) > 2;


-- Câu 5
CREATE VIEW vCau5 AS
SELECT TINH.TENTINH, COUNT(CAUTHU.MACT) AS SoLuongCauThuTienDao
FROM TINH
INNER JOIN CAULACBO ON TINH.MATINH = CAULACBO.MATINH
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
WHERE CAUTHU.VITRI = N'Tiền Đạo'
GROUP BY TINH.TENTINH;



--Câu 6
create view vCau6 as
select SANVD.TENSAN, TINH.TENTINH from CAULACBO 
join BANGXH on CAULACBO.MACLB = BANGXH.MACLB
join SANVD on CAULACBO.MASAN = SANVD.MASAN
join TINH on CAULACBO.MATINH = CAULACBO.MATINH
where BANGXH.NAM = 2009 and BANGXH.VONG = 3 and BANGXH.HANG = 1


-- Câu 7
create view vCau7 as
select HUANLUYENVIEN.TENHLV from HUANLUYENVIEN
join HLV_CLB on HLV_CLB.MAHLV = HUANLUYENVIEN.MAHLV
where HUANLUYENVIEN.DIENTHOAI = ''

select * from vCau7


-- Câu 8
CREATE VIEW vCau8 AS
SELECT HUANLUYENVIEN.MAHLV, HUANLUYENVIEN.TENHLV
FROM HUANLUYENVIEN
LEFT JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
WHERE HUANLUYENVIEN.MAQG = 'VN' 
AND HLV_CLB.MAHLV IS NULL;



-- Câu 9
create view vCau9 as
select TRANDAU.NGAYTD, SANVD.TENSAN, CLB1.TENCLB as 'TenCLB1', CLB2.TENCLB as 'TenCLB2', KETQUA from TRANDAU
join BANGXH on TRANDAU.MACLB1 = BANGXH.MACLB or TRANDAU.MACLB2 = BANGXH.MACLB
join CAULACBO CLB1 on CLB1.MACLB = TRANDAU.MACLB1
join CAULACBO CLB2 on CLB2.MACLB = TRANDAU.MACLB2
join SANVD on SANVD.MASAN = TRANDAU.MASAN
where BANGXH.HANG = 1 and BANGXH.VONG <= 3 and BANGXH.NAM = 2009


-- Câu 10
CREATE VIEW vCau10 AS
SELECT TD.NGAYTD, SD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD
INNER JOIN SANVD SD ON TD.MASAN = SD.MASAN
INNER JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.VONG = 3
    AND TD.NAM = 2009
    AND (
        TD.MACLB1 = (
            SELECT TOP 1 MACLB
            FROM BANGXH
            WHERE VONG = 3 AND NAM = 2009
            ORDER BY HANG ASC
        )
        OR TD.MACLB2 = (
            SELECT TOP 1 MACLB
            FROM BANGXH
            WHERE VONG = 3 AND NAM = 2009
            ORDER BY HANG ASC
        )
    )
go

-----------------------------------------------------
grant select on dbo.vCau1 to BDRead
grant select on dbo.vCau2 to BDRead
grant select on dbo.vCau3 to BDRead
grant select on dbo.vCau4 to BDRead
grant select on dbo.vCau5 to BDRead
grant select on dbo.vCau6 to BDRead
grant select on dbo.vCau7 to BDRead
grant select on dbo.vCau8 to BDRead
grant select on dbo.vCau9 to BDRead
grant select on dbo.vCau10 to BDRead


grant select on dbo.vCau5 to BDU01
grant select on dbo.vCau6 to BDU01
grant select on dbo.vCau7 to BDU01
grant select on dbo.vCau8 to BDU01
grant select on dbo.vCau9 to BDU01
grant select on dbo.vCau10 to BDU01


grant select on dbo.vCau1 to BDU03
grant select on dbo.vCau2 to BDU03
grant select on dbo.vCau3 to BDU03
grant select on dbo.vCau4 to BDU03


grant select on dbo.vCau1 to BDU04
grant select on dbo.vCau2 to BDU04
grant select on dbo.vCau3 to BDU04
grant select on dbo.vCau4 to BDU04