/*---------------------------------------------------------- 
MASV: 47.01.104.169
HO TEN: Trần Duy Quân
LAB: 04
NGAY: 08/04/2024
----------------------------------------------------------*/
CREATE TABLE NHANVIEN(
MANV VARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) not null,
EMAIL VARCHAR(20),
LUONG VARBINARY(MAX),
TENDN NVARCHAR(100) not null,
MATKHAU VARBINARY(MAX)
)
go
CREATE TABLE LOP
(
MALOP VARCHAR(20) PRIMARY KEY,
TENLOP NVARCHAR(100),
MANV VARCHAR(20)
CONSTRAINT NHANVIEN_LOP FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
)
GO
CREATE TABLE SINHVIEN
(
MASV NVARCHAR(20) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATETIME,
DIACHI VARCHAR(200),
MALOP VARCHAR(20),
TENDN NVARCHAR(100) NOT NULL,
MATKHAU VARBINARY(MAX) NOT NULL,
CONSTRAINT SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)
go

INSERT INTO LOP (MALOP, TENLOP, MANV)
VALUES ('L001', N'Lớp 1', 'NV01'),
       ('L002', N'Lớp 2', 'NV02'),
       ('L003', N'Lớp 3', 'NV02');
INSERT INTO NHANVIEN (MANV
,HOTEN 
,EMAIL 
,LUONG 
,TENDN
,MATKHAU)
VALUES (N'NV001', N'Nguyễn Văn A','nva@example.com',5000000,N'nva', null)